name: l10n_esperanto
description: Esperanto localization for Flutter.
version: 2.0.1
homepage: https://github.com/deakjahn/l10n_esperanto

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0

flutter:
  uses-material-design: true
