name: l10n_esperanto
description: Esperanto localization for Flutter.
version: 1.0.0
homepage: https://github.com/deakjahn/l10n_esperanto

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.16.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.9.0

flutter:
  uses-material-design: true
